#!/usr/bin/env python

import getpass
import telnetlib

#ask for username and password
user = raw_input("Enter your telnet username: ")
password = getpass.getpass()

#open a file called switch-ip
f = open("switch-ip")

#telnet to switches and get running config
for line in f:
    print "Getting running config from switch " + (line)
    HOST = line.strip()
    tn = telnetlib.Telnet(HOST)

    tn.read_until("Username: ")
    tn.write(user + "\n")
    if password:
        tn.read_until("Password: ")
        tn.write(password + "\n")

    tn.write("term len 0\n")
    tn.write("show run\n")
    tn.write("exit\n")

    readoutput = tn.read_all()
    saveoutput = open("switch" + HOST, "w")
    saveoutput.write(readoutput)
    saveoutput.close
